# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - netcdf-bin
    - libnetcdf-dev
    
script:
  - travis_wait 30 R CMD build .
  - travis_wait 30 R CMD check *.tar.gz

after_success:
  - travis_wait 30 Rscript -e 'covr::codecov()'
